# Generated by Django 5.0.6 on 2026-04-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('HARSH_BRAKE', 'Harsh Brake'), ('RAPID_ACCEL', 'Rapid Acceleration'), ('OVERSPEED', 'Overspeed')], max_length=20)),
                ('severity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('speed_before', models.FloatField(null=True)),
                ('speed_after', models.FloatField(null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', 'timestamp'], name='events_driv_vehicle_ee9745_idx'), models.Index(fields=['driver', 'timestamp'], name='events_driv_driver__3a4d5a_idx')],
            },
        ),
    ]
