# Generated by Django 5.0.6 on 2026-04-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('km_driven', models.FloatField(default=0.0)),
                ('window_Days', models.IntegerField(default=30)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='drivers.driver')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['driver', 'calculated_at'], name='scoring_dri_driver__ac6e95_idx')],
            },
        ),
    ]
