# Generated by Django 5.0.6 on 2026-04-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('speed', models.FloatField()),
                ('fuel_level', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', 'timestamp'], name='telemetry_t_vehicle_efa0a8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='telemetry',
            constraint=models.UniqueConstraint(fields=('vehicle', 'source_id'), name='unique_telemetry_source'),
        ),
    ]
